### ISSUE TITLE
Add GitLab ressources

### ISSUE THREAD

**Issue by jeanphibaconnais** [milanm/DevOps-Roadmap#7]
Hi 👋 
About GitLab, I purpose you their free DevOps book (https://page.gitlab.com/resources-ebook-beginners-guide-devops.html) and a personal serie of GitLab CheatCheet. I don't know if this last one have this place in this repo. Don't hesitate to tell me.

**Comment by milanm** [comment]
Yes, Jean-Phi it make sense. Lets see where to put it.
